const db = require("../config/db.js");

// Initialize users table if it doesn't exist
const initializeTable = async () => {
  const queryUsers = `
    CREATE TABLE IF NOT EXISTS users (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username VARCHAR(100) UNIQUE NOT NULL,
      email VARCHAR(255) UNIQUE,
      password_hash TEXT NOT NULL,
      role VARCHAR(20) DEFAULT 'guest',
      is_active BOOLEAN DEFAULT TRUE,
      reset_token VARCHAR(255) NULL,
      reset_token_expires TIMESTAMP NULL,
      last_login_at TIMESTAMP NULL,
      last_read_notifications_at TIMESTAMP NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
  `;

  try {
    await db.query(queryUsers);
    console.log("Database table 'users' verified/created successfully.");
    
    // Seed admin account if it does not exist
    const checkAdmin = await db.query("SELECT * FROM users WHERE username = 'admin';");
    if (checkAdmin.rows.length === 0) {
      await db.query(`
        INSERT INTO users (username, email, password_hash, role)
        VALUES ('admin', 'admin@valtour.com', '123456', 'admin');
      `);
      console.log("Admin account (admin/123456) seeded successfully.");
    }
  } catch (err) {
    console.error("Error creating/seeding 'users' table:", err);
  }
};

// Auto-run initialization
initializeTable();

const User = {
  create: async (userData) => {
    const { username, email, password } = userData;

    const query = `
      INSERT INTO users (username, email, password_hash, role)
      VALUES ($1, $2, $3, 'guest')
      RETURNING id, username, email, role, created_at;
    `;
    const values = [username, email, password];
    const res = await db.query(query, values);
    return res.rows[0];
  },

  findByUsername: async (username) => {
    const query = `SELECT * FROM users WHERE username = $1;`;
    const res = await db.query(query, [username]);
    return res.rows[0];
  },

  findByEmail: async (email) => {
    const query = `SELECT * FROM users WHERE email = $1;`;
    const res = await db.query(query, [email]);
    return res.rows[0];
  },

  findById: async (id) => {
    const query = `SELECT * FROM users WHERE id = $1;`;
    const res = await db.query(query, [id]);
    return res.rows[0];
  },

  findByUsernameExcludeId: async (username, id) => {
    const query = `SELECT * FROM users WHERE username = $1 AND id != $2;`;
    const res = await db.query(query, [username, id]);
    return res.rows[0];
  },

  findByEmailExcludeId: async (email, id) => {
    const query = `SELECT * FROM users WHERE email = $1 AND id != $2;`;
    const res = await db.query(query, [email, id]);
    return res.rows[0];
  },

  updateProfile: async (id, { username, email, password }) => {
    const query = `
      UPDATE users
      SET username = $1, email = $2, password_hash = $3
      WHERE id = $4
      RETURNING id, username, email, role, created_at;
    `;
    const res = await db.query(query, [username, email, password, id]);
    return res.rows[0];
  },

  updatePasswordByEmail: async (email, newPassword) => {
    const query = `
      UPDATE users
      SET password_hash = $1
      WHERE email = $2
      RETURNING id, username, email, role;
    `;
    const res = await db.query(query, [newPassword, email]);
    return res.rows[0];
  },

  getAll: async () => {
    const query = `SELECT id, username, email, role, created_at FROM users ORDER BY id ASC;`;
    const res = await db.query(query);
    return res.rows;
  },

  createWithRole: async (userData) => {
    const { username, email, password, role } = userData;
    const query = `
      INSERT INTO users (username, email, password_hash, role)
      VALUES ($1, $2, $3, $4)
      RETURNING id, username, email, role, created_at;
    `;
    const values = [username, email, password, role || 'guest'];
    const res = await db.query(query, values);
    return res.rows[0];
  },

  delete: async (id) => {
    const query = `DELETE FROM users WHERE id = $1 RETURNING id, username, email;`;
    const res = await db.query(query, [id]);
    return res.rows[0];
  },

  updateRole: async (id, role) => {
    const query = `
      UPDATE users
      SET role = $1
      WHERE id = $2
      RETURNING id, username, email, role, created_at;
    `;
    const res = await db.query(query, [role, id]);
    return res.rows[0];
  }
};

module.exports = User;
